name: xnap-example
channels:
- pytorch
- defaults
dependencies:
- python==3.8
- pip
- pip:
  - torch
  - torchvision
  - torchaudio
  - onnx
  - wandb
  - onnxruntime
  - ipykernel
- numpy
- tqdm
- tensorboard
- protobuf

